### ISSUE TITLE
Add checkboxes and checkbox functionality to ISPSelectWithIncidents

### ISSUE THREAD

**Issue by roman-rosenast** [amysorto/mlab-vis-client#7]

**Comment by amysorto** [comment]
Started working on this. Now we have a list of all the options (and an incident icon appearing with those that have incidents) listed out.

Although I haven't done much to style it as a dropdown. I suggest looking at these links for a good starter point to make our custom dropdown:
https://stackoverflow.com/questions/19206919/how-to-create-checkbox-inside-dropdown
https://andrejgajdos.com/custom-select-dropdown/

Some of them make their own icon for a dropdown arrow. Although I think it might be a good idea to use the existing Icon component in this project and onClick somehow.

**Comment by amysorto** [comment]
I have worked on issue #10. The only thing that is happening now is that when you try to add an ISP, nothing is updating. I created a bug for that (#15). Aside from that, the main thing left for this issue is styling the list and making it look like a dropdown.
